server:
  servlet:
    context-path: /helphe-desk/api
    
spring:    
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/helphedeskDB
      auto-index-creation: true
      
springdoc:
  swagger-ui:
    path: /public/swagger

helphe-desk:    
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}