server:
  servlet:
    context-path: /helphe-desk/api
    
spring:    
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/helphedeskDB
      auto-index-creation: true